apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}
  labels:
    app: {{ template "mpijob.fullname" . }}-serviceaccount
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    type: {{ template "type" . }}
    role: {{ template "roles.config" . }}
    app.kubernetes.io/name: {{ template "mpijob.fullname" . }}-serviceaccount
    app.kubernetes.io/instance: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    app.kubernetes.io/version: "{{ .Chart.Version }}"
    app.kubernetes.io/part-of: {{ template "type" . }}
    app.kubernetes.io/component: {{ template "roles.config" . }}
    app.kubernetes.io/managed-by: "helm"
