apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "polyaxon.fullname" . }}-api
  annotations:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    checksum/config: {{ include (print $.Template.BasePath "/cm.yaml") . | sha256sum }}
    checksum/secrets: {{ include (print $.Template.BasePath "/secrets.yaml") . | sha256sum }}
  labels:
    app: {{ template "polyaxon.fullname" . }}-api
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    type: {{ .Values.types.core }}
    role: {{ .Values.roles.api }}
    app.kubernetes.io/name: {{ template "polyaxon.fullname" . }}-api
    app.kubernetes.io/instance: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    app.kubernetes.io/version: "{{ .Chart.Version }}"
    app.kubernetes.io/part-of: {{ .Values.types.core }}
    app.kubernetes.io/component: {{ .Values.roles.api }}
    app.kubernetes.io/managed-by: "helm"
spec:
  replicas: {{ .Values.api.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ template "polyaxon.fullname" . }}-api
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      annotations:
        chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
        checksum/config: {{ include (print $.Template.BasePath "/cm.yaml") . | sha256sum }}
        checksum/secrets: {{ include (print $.Template.BasePath "/secrets.yaml") . | sha256sum }}
      labels:
        app: {{ template "polyaxon.fullname" . }}-api
        release: "{{ .Release.Name }}"
        type: {{ .Values.types.core }}
        role: {{ .Values.roles.api }}
        app.kubernetes.io/name: {{ template "polyaxon.fullname" . }}-api
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
{{ include "securityContext" . | indent 6 }}
{{ include "config.scheduling" . | indent 6 }}
{{ include "config.sa" . | indent 6 }}
      containers:
      - name: {{ .Chart.Name }}-api
        image: "{{ .Values.api.image }}:{{ .Values.api.imageTag }}"
        imagePullPolicy: {{ .Values.api.imagePullPolicy }}
        ports:
        - containerPort: {{ .Values.api.service.internalPort }}
        envFrom:
{{ include "config.envFrom" . | indent 8 }}
        env:
{{ include "config.dns" . | indent 8 }}
{{ include "config.envs" . | indent 8 }}
{{ include "config.persistence.outputs" . | indent 8 }}
{{ include "config.persistence.data" . | indent 8 }}
{{ include "config.persistence.logs" . | indent 8 }}
{{ include "config.persistence.upload" . | indent 8 }}
{{ include "config.persistence.repos" . | indent 8 }}
{{ include "config.storesSecrets.outputs" . | indent 8 }}
{{ include "config.storesSecrets.logs" . | indent 8 }}
{{ include "config.debugMode" . | indent 8 }}
        volumeMounts:
{{ include "volumes.volumeMounts.logs" . | indent 8}}
{{ include "volumes.volumeMounts.outputs" . | indent 8}}
{{ include "volumes.volumeMounts.repos" . | indent 8}}
{{ include "volumes.volumeMounts.upload" . | indent 8}}
{{ include "volumes.volumeMounts.ssl" . | indent 8}}
{{ include "volumes.dirMounts" . | indent 8}}
        livenessProbe:
          failureThreshold: 10
          httpGet:
            path: /healthz/
            port: {{ .Values.api.service.internalPort }}
            scheme: {{ .Values.api.service.scheme | default "HTTP" }}
            {{- if .Values.allowedHosts }}
            httpHeaders:
              - name: Host
                value: {{ template "polyaxon.fullname" . }}-api
            {{- end }}
          initialDelaySeconds: 150
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 2
        readinessProbe:
          failureThreshold: 30
          httpGet:
            path: /healthz/
            port: {{ .Values.api.service.internalPort }}
            scheme: {{ .Values.api.service.scheme | default "HTTP" }}
            {{- if .Values.allowedHosts }}
            httpHeaders:
              - name: Host
                value: {{ template "polyaxon.fullname" . }}-api
            {{- end }}
          initialDelaySeconds: 150
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 2
        resources:
          requests:
{{ toYaml .Values.api.resources.requests | indent 12 }}
          {{- if .Values.limitResources }}
          limits:
{{ toYaml .Values.api.resources.limits | indent 12 }}
          {{- end }}
      - name: {{ .Chart.Name }}-streams
        image: "{{ .Values.streams.image }}:{{ .Values.streams.imageTag }}"
        imagePullPolicy: {{ .Values.streams.imagePullPolicy }}
        ports:
        - containerPort: {{ .Values.streams.service.internalPort }}
        envFrom:
{{ include "config.envFrom" . | indent 8 }}
        env:
{{ include "config.envs" . | indent 8 }}
        livenessProbe:
          failureThreshold: 10
          httpGet:
            path: /healthz/
            port: {{ .Values.streams.service.internalPort }}
            scheme: {{ .Values.streams.service.scheme | default "HTTP" }}
          initialDelaySeconds: 100
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 2
        readinessProbe:
          failureThreshold: 30
          httpGet:
            path: /healthz/
            port: {{ .Values.streams.service.internalPort }}
            scheme: {{ .Values.streams.service.scheme | default "HTTP" }}
          initialDelaySeconds: 150
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 2
        resources:
          requests:
{{ toYaml .Values.streams.resources.requests | indent 12 }}
          {{- if .Values.limitResources }}
          limits:
{{ toYaml .Values.streams.resources.limits | indent 12 }}
          {{- end }}
      volumes:
{{ include "volumes.volumes.logs" . | indent 6}}
{{ include "volumes.volumes.outputs" . | indent 6}}
{{ include "volumes.volumes.repos" . | indent 6}}
{{ include "volumes.volumes.upload" . | indent 6}}
{{ include "volumes.volumes.ssl" . | indent 6}}
{{ include "volumes.dirs" . | indent 6 }}
