apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "polyaxon.fullname" . }}-api
  annotations:
    checksum/config: {{ include (print $.Template.BasePath "/cm.yaml") . | sha256sum }}
  labels:
    app: {{ template "polyaxon.fullname" . }}-api
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    type: {{ .Values.types.core }}
    role: {{ .Values.roles.api }}
spec:
  replicas: {{ .Values.api.replicas }}
  template:
    metadata:
      labels:
        app: {{ template "polyaxon.fullname" . }}-api
        release: "{{ .Release.Name }}"
        type: {{ .Values.types.core }}
        role: {{ .Values.roles.api }}
    spec:
      {{- if .Values.nodeSelectors.core }}
      nodeSelector:
{{ toYaml .Values.nodeSelectors.core | indent 8 }}
      {{- end }}
      {{- if .Values.affinity }}
      affinity:
{{ toYaml .Values.affinity | indent 8 }}
      {{- end }}
      {{- if .Values.tolerations.core }}
      tolerations:
{{ toYaml .Values.tolerations.core | indent 8 }}
      {{- end }}
      serviceAccountName: {{ template "polyaxon.fullname" . }}-serviceaccount
      containers:
      - name: {{ .Chart.Name }}-api
        image: "{{ .Values.api.image }}:{{ .Values.api.imageTag }}"
        imagePullPolicy: {{ .Values.api.imagePullPolicy }}
        ports:
        - containerPort: {{ .Values.api.service.internalPort }}
        env:
        {{ include "config.core" . | indent 8 }}
        {{ include "config.amqp" . | indent 8 }}
        {{ include "config.celery" . | indent 8 }}
        {{ include "config.db" . | indent 8 }}
        {{ include "config.dirs" . | indent 8 }}
        {{ include "config.emails" . | indent 8 }}
        {{ include "config.k8s" . | indent 8 }}
        {{ include "config.registry" . | indent 8 }}
        {{ include "config.spawner" . | indent 8 }}
        {{ include "config.versions" . | indent 8 }}
        {{ include "config.redis" . | indent 8 }}
        volumeMounts:
        {{ include "volumes.volumeMounts.logs" . | indent 8}}
        {{ include "volumes.volumeMounts.outputs" . | indent 8}}
        {{ include "volumes.volumeMounts.repos" . | indent 8}}
        {{ include "volumes.volumeMounts.upload" . | indent 8}}
        {{ include "volumes.dirMounts" . | indent 8}}
        livenessProbe:
          failureThreshold: 10
          httpGet:
            path: /_health/
            port: {{ .Values.api.service.internalPort }}
            scheme: HTTP
          initialDelaySeconds: 100
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 2
        readinessProbe:
          failureThreshold: 30
          httpGet:
            path: /_health/
            port: {{ .Values.api.service.internalPort }}
            scheme: HTTP
          initialDelaySeconds: 150
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 2
        resources:
          requests:
{{ toYaml .Values.api.resources.requests | indent 12 }}
          {{- if .Values.limitResources }}
          limits:
{{ toYaml .Values.api.resources.limits | indent 12 }}
          {{- end }}
      - name: {{ .Chart.Name }}-streams
        image: "{{ .Values.streams.image }}:{{ .Values.streams.imageTag }}"
        imagePullPolicy: {{ .Values.streams.imagePullPolicy }}
        ports:
        - containerPort: {{ .Values.streams.service.internalPort }}
        env:
        {{ include "config.core" . | indent 8 }}
        {{ include "config.amqp" . | indent 8 }}
        {{ include "config.celery" . | indent 8 }}
        {{ include "config.db" . | indent 8 }}
        {{ include "config.dirs" . | indent 8 }}
        {{ include "config.emails" . | indent 8 }}
        {{ include "config.k8s" . | indent 8 }}
        {{ include "config.persistence.outputs" . | indent 8 }}
        {{ include "config.persistence.data" . | indent 8 }}
        {{ include "config.persistence.logs" . | indent 8 }}
        {{ include "config.persistence.upload" . | indent 8 }}
        {{ include "config.persistence.repos" . | indent 8 }}
        {{ include "config.registry" . | indent 8 }}
        {{ include "config.spawner" . | indent 8 }}
        {{ include "config.versions" . | indent 8 }}
        {{ include "config.redis" . | indent 8 }}
        resources:
          requests:
{{ toYaml .Values.streams.resources.requests | indent 12 }}
          {{- if .Values.limitResources }}
          limits:
{{ toYaml .Values.streams.resources.limits | indent 12 }}
          {{- end }}
      volumes:
      {{ include "volumes.volumes.logs" . | indent 6}}
      {{ include "volumes.volumes.outputs" . | indent 6}}
      {{ include "volumes.volumes.repos" . | indent 6}}
      {{ include "volumes.volumes.upload" . | indent 6}}
      {{ include "volumes.dirs" . | indent 6 }}
