apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "polyaxon.fullname" . }}-api
  annotations:
    checksum/config: {{ include (print $.Template.BasePath "/plx-configmap.yaml") . | sha256sum }}
  labels:
    app: {{ template "polyaxon.fullname" . }}-api
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    type: {{ .Values.types.core }}
    role: {{ .Values.roles.api }}
spec:
  replicas: {{ .Values.api.replicas }}
  template:
    metadata:
      labels:
        app: {{ template "polyaxon.fullname" . }}-api
        release: "{{ .Release.Name }}"
        type: {{ .Values.types.core }}
        role: {{ .Values.roles.api }}
    spec:
    {{- if .Values.nodeSelectors.core }}
      nodeSelector:
{{ toYaml .Values.nodeSelectors.core | indent 8 }}
      {{- end }}
      {{- if .Values.affinity.core }}
      affinity:
{{ toYaml .Values.affinity.core | indent 8 }}
      {{- end }}
      {{- if .Values.tolerations.core }}
      tolerations:
{{ toYaml .Values.tolerations.core | indent 8 }}
      {{- end }}
      serviceAccountName: {{ template "polyaxon.fullname" . }}-serviceaccount
      containers:
      - name: {{ .Chart.Name }}-api
        image: "{{ .Values.api.image }}:{{ .Values.api.imageTag }}"
        imagePullPolicy: {{ .Values.api.imagePullPolicy }}
        ports:
        - containerPort: {{ .Values.api.service.internalPort }}
        env:
        {{ include "config.global" . | indent 8 }}
        {{ include "config.versions" . | indent 8 }}
        {{ include "config.django" . | indent 8 }}
        {{ include "config.registry" . | indent 8 }}
        {{ include "config.db" . | indent 8 }}
        {{ include "config.redis" . | indent 8 }}
        {{ include "config.amqp" . | indent 8 }}
        {{ include "config.routingKeys" . | indent 8 }}
        {{ include "config.queues" . | indent 8 }}
        {{ include "config.intervals" . | indent 8 }}
        {{ include "config.mount_paths" . | indent 8 }}
        {{ include "config.sub_paths" . | indent 8 }}
        {{ include "config.claim_names" . | indent 8 }}
        {{ include "config.config.dirs" . | indent 8 }}
        volumeMounts:
        {{ include "volumes.volumeMounts" . | indent 8}}
        livenessProbe:
          failureThreshold: 5
          httpGet:
            path: /_health/
            port: {{ .Values.api.service.internalPort }}
            scheme: HTTP
          initialDelaySeconds: 100
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 2
        readinessProbe:
          failureThreshold: 10
          httpGet:
            path: /_health/
            port: {{ .Values.api.service.internalPort }}
            scheme: HTTP
          initialDelaySeconds: 100
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 2
        resources:
{{ toYaml .Values.api.resources | indent 10 }}
      - name: {{ .Chart.Name }}-api-events
        image: "{{ .Values.apiEvents.image }}:{{ .Values.apiEvents.imageTag }}"
        imagePullPolicy: {{ .Values.api.imagePullPolicy }}
        ports:
        - containerPort: {{ .Values.apiEvents.service.internalPort }}
        env:
        {{ include "config.global" . | indent 8 }}
        {{ include "config.versions" . | indent 8 }}
        {{ include "config.django" . | indent 8 }}
        {{ include "config.registry" . | indent 8 }}
        {{ include "config.db" . | indent 8 }}
        {{ include "config.redis" . | indent 8 }}
        {{ include "config.amqp" . | indent 8 }}
        {{ include "config.routingKeys" . | indent 8 }}
        {{ include "config.queues" . | indent 8 }}
        {{ include "config.intervals" . | indent 8 }}
        {{ include "config.mount_paths" . | indent 8 }}
        {{ include "config.sub_paths" . | indent 8 }}
        {{ include "config.claim_names" . | indent 8 }}
        {{ include "config.config.dirs" . | indent 8 }}
        resources:
{{ toYaml .Values.apiEvents.resources | indent 10 }}
      volumes:
      {{ include "volumes.volumes" . | indent 6 }}
