apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "polyaxon.fullname" . }}-config
  labels:
    app: {{ template "polyaxon.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    type: {{ .Values.types.core }}
    role: {{ .Values.roles.config }}
    app.kubernetes.io/name: {{ template "polyaxon.fullname" . }}-config
    app.kubernetes.io/instance: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    app.kubernetes.io/version: "{{ .Chart.Version }}"
    app.kubernetes.io/part-of: {{ .Values.types.core }}
    app.kubernetes.io/component: {{ .Values.types.config }}
    app.kubernetes.io/managed-by: "helm"
data:
  # Cluster
  POLYAXON_DEPLOYMENT_TYPE: {{ default "kubernetes" .Values.deploymentType | quote }}
  {{- if .Values.ingress.enabled }}
  POLYAXON_API_HOST: {{ .Values.ingress.hostName | quote }}
  {{- else }}
  {{- if .Values.hostName }}
  POLYAXON_API_HOST: {{ .Values.hostName | quote }}
  {{- else }}
  {{- if eq .Values.gateway.service.type "NodePort" }}
  POLYAXON_API_HOST: http://{{ template "polyaxon.fullname" . }}-gateway:{{ .Values.gateway.service.nodePort }}
  {{- else }}
  POLYAXON_API_HOST: http://{{ template "polyaxon.fullname" . }}-gateway:{{ .Values.gateway.service.port }}
  {{- end }}
  {{- end }}
  {{- end }}
  POLYAXON_K8S_NAMESPACE: {{ .Values.namespace | quote }}
  POLYAXON_K8S_APP_SECRET_NAME: {{ template "polyaxon.fullname" . }}-secret
  {{- if .Values.logLevel }}
  POLYAXON_LOG_LEVEL: {{ default "WARNING" .Values.logLevel | quote }}
  {{- end }}
  POLYAXON_ENVIRONMENT: {{ default "production" .Values.environment | quote }}
  POLYAXON_TIME_ZONE: {{ .Values.timezone | quote }}
  # Versions
  POLYAXON_CHART_VERSION: {{ .Chart.Version | quote }}
