dist: xenial

language: python

python:
  - "3.6"

services:
  - docker

env:
  matrix:
  - VERSION=1.13


install:
  - . "ci/envs/minikube-${VERSION}.env"
  - ./ci/install.sh
script:
  - ./ci/test-deploy.sh

notifications:
  slack:
    secure: vnjcwdqGj7bVumr2SWs5ZqTG/uRnqYA8w6WFBpns7xFAXNocYnWlSvaqTiY+6zoEVOBJcOQyRWpxpLGMTnoel3JgtWES6OTDRnq+439Hdb6d2hbO5/Pt1i/M0ypnYwZxIOeKa1Q1XEOBvxFhru/9ljjmqiZLjNs+FxvINPAUb0OiNxqVZI65oQp2G6ulqiIuTS5e0Qn8bg0r8khm1BOUJibGDjKw6GRxjZr61duQGe2uK79ZuKDKomARIWIHZyum1TQMk+tN0t/0cxgdsG3RrQM1wxQMm1eO6AEl2zm0xpBWz5lO2eHTj5fBGGl9dj1/V6AnmNMPLvlzG827C5y6GCLjhBVngX/aZcxvOwgB1NNopzn2VdBoPds6dAenNGPCsCnnJQT8KEIwu9gQ7x3EvYuc2dbHJo6IO57+8S5jpB32VQVadSjdz4e61ia8KCNEoqHEy2ctGp2zQXw8AocdQ//3BwGsjU4nbeFVuJgM2gajQSaXOJXzo4j2F09hvK4fPPTwKXrDPKQoZes1io7uSi8EFH/+7SBXSYEHGnICcl/aBQw/M6aojG6wxJR/7wCmcg/XvAIasq8HGF8N9vi6QK3gEgcUqjEUCVYF7GC+0LJQYdB+00KSOiTmmHZjGYIgTDDYVKsDz1XbTYZGK4Q/+ijWZTnDOtDlKzXFr3xoeB0=
