esudo: required
dist: trusty
language: python
python:
  - "3.5"
  - "3.6"

env:
  global:
    - DJANGO_SETTINGS_MODULE=polyaxon.settings
    - PYTHONPATH=$HOME/builds/polyaxon
    - PIP_USE_MIRRORS=true

services:
  - postgresql
  - redis-server

addons:
  postgresql: "9.6"

before_install:
  - if [[ "$TRAVIS_PYTHON_VERSION" == "3.6" ]]; then
      ./config/build_docker.sh "$TRAVIS_BRANCH";
    fi

install:
  # http://conda.pydata.org/docs/travis.html
  - sudo apt-get update
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a

  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION numpy scipy pytest-cov h5py
  - source activate test-environment
#  - python setup.py -q install
  - pip install -r requirements/requirements-test.txt
  - pip install codecov

before_script:
  - psql -c "CREATE DATABASE travis_ci_test;" -U postgres
  - cp config/local.json polyaxon/polyaxon/env_vars/local.json

script:
  - py.test tests -v

notifications:
  slack:
    secure: l4+kfVek4PU6EekvWpvumsfAx8gvp0QuyQmrYIC9K0Dojk2BVBAT1QFY9A5hwSUvB8YkzDKw5/HYM5Op0sJsUljzpLaIXUAd1YFR3LhcOO8ZOxLl9+rOPDfvgDbTzXoJ2fSAr58MnHbB7gh14m/2Xg/GowCvWOTxnBU0/8l6mAuFg8I09sxBHi/5gc6OkAHVb6JHX0BFfd2W/TaDPvjND2h2JF3HQTxYn6uJ+Ud3hwUq2W8mrbFBJD40mtVOfXx/UJBT5nAZXdySUZWSAcOy/8MnPELZCF8XEGHNaKaWCO3hyazSeMWcLc8iu6etLr0AIg9vjgPNT3XmHS3tWCevfc6FA9uUoHvfiV5TO4rzDAmZjuMawv6V5eIH60+JtbA3Nuu+qu3rbuqLVgxQPFRUhRA7RV6UBMToKu6kssfLVw/ymPCQodLIMxaJ+Nej1EtYLPXHeHX2+lrSwauAYNnpeiXFs3EjpSYtAs6NdgL9vXIyDYzUUhrWvKDWSFjrEU0H/KIkq00OQlNcPOayFP3a00uEn6P9NDdtCYbhVPMC20YQxPqIAHOqJfwbQUw+VzP+1Xgx5LACqhMX1T3n02sn3H7BOrK8PgxV+T4rDCLsPo2BPdzQH8zTCFM0hANDC2s2cmi1irEsCm51yFGgZwllXWeCIzaoRmvbbdjdNjoWeAk=
