version: "3.4"

x-defaults: &defaults
  env_file:
  - compose/components.env

services:
  postgres:
    image: postgres:12.3-alpine
    environment:
      POSTGRES_USER: "polyaxon"
      POSTGRES_PASSWORD: "polyaxon"
    networks:
      - polyaxon

  redis:
    image: redis:5.0.4-alpine
    networks:
      - polyaxon

  api:
    <<: *defaults
    build:
      context: .
      dockerfile: ./platform/coreapi/Dockerfile.dev
    networks:
      - polyaxon
    depends_on:
      - postgres
      - redis
    volumes:
      - ./static:/polyaxon/static
      - ./public:/polyaxon/public
      - ./platform:/polyaxon/platform
      - ./core:/polyaxon/core
      - ~/.kube:/root/.kube
    ports:
      - "8000:8000"
      - "8001:8001"
      - "8000:80"
      - "9000:443"
    environment:
      DATABASE_URL: "postgres://polyaxon:polyaxon@postgres:5432/polyaxon"

  scheduler:
    <<: *defaults
    build:
      context: .
      dockerfile: ./platform/core-scheduler/Dockerfile.dev
    networks:
    - polyaxon
    depends_on:
    - postgres
    - redis
    volumes:
      - ./platform:/polyaxon/platform
      - ./core:/polyaxon/core
      - ~/.kube:/root/.kube
    environment:
      DATABASE_URL: "postgres://polyaxon:polyaxon@postgres:5432/polyaxon"
      #      POLYAXON_LOG_LEVEL: DEBUG

networks:
  polyaxon:

