apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "mpijob.fullname" . }}-clusterrole-binding
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    type: {{ template "type" . }}
    role: {{ template "roles.config" . }}
    app.kubernetes.io/name: {{ template "mpijob.fullname" . }}-clusterrole-binding
    app.kubernetes.io/instance: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    app.kubernetes.io/version: "{{ .Chart.Version }}"
    app.kubernetes.io/part-of: {{ template "type" . }}
    app.kubernetes.io/component: {{ template "roles.config" . }}
    app.kubernetes.io/managed-by: "helm"
subjects:
- kind: ServiceAccount
  name: {{ .Release.Name }}-{{ .Chart.Name }}
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Release.Name }}-{{ .Chart.Name }}
