apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "polyaxon.fullname" . }}-api
  annotations:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    checksum/proxies-config: {{ include (print $.Template.BasePath "/proxies-cm.yaml") . | sha256sum }}
{{ include "config.checksum.platform" . | indent 4 }}
  labels:
    app: {{ template "polyaxon.fullname" . }}-api
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    type: {{ .Values.types.core }}
    role: {{ .Values.roles.api }}
    app.kubernetes.io/name: {{ template "polyaxon.fullname" . }}-api
    app.kubernetes.io/instance: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    app.kubernetes.io/version: "{{ .Chart.Version }}"
    app.kubernetes.io/part-of: {{ .Values.types.core }}
    app.kubernetes.io/component: {{ .Values.roles.api }}
    app.kubernetes.io/managed-by: "helm"
spec:
  replicas: {{ .Values.api.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ template "polyaxon.fullname" . }}-api
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      annotations:
        chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
        checksum/proxies-config: {{ include (print $.Template.BasePath "/proxies-cm.yaml") . | sha256sum }}
{{ include "config.checksum.platform" . | indent 8 }}
      labels:
        app: {{ template "polyaxon.fullname" . }}-api
        release: "{{ .Release.Name }}"
        type: {{ .Values.types.core }}
        role: {{ .Values.roles.api }}
        app.kubernetes.io/name: {{ template "polyaxon.fullname" . }}-api
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
{{ include "securityContext" . | indent 6 }}
{{ include "config.scheduling" . | indent 6 }}
{{ include "config.sa" . | indent 6 }}
{{ include "config.imagePullSecrets" . | indent 6}}
      containers:
      - name: {{ .Chart.Name }}-api
        image: "{{ .Values.api.image }}:{{ .Values.api.imageTag }}"
        imagePullPolicy: {{ .Values.api.imagePullPolicy }}
        ports:
        - containerPort: {{ .Values.api.service.targetPort }}
        envFrom:
{{ include "config.envFrom.common" . | indent 8 }}
{{ include "config.envFrom.secret" . | indent 8 }}
{{ include "config.envFrom.platform" . | indent 8 }}
{{ include "config.envFrom.proxies" . | indent 8 }}
        env:
{{ include "config.envs" . | indent 8 }}
{{ include "config.debugMode" . | indent 8 }}
        livenessProbe:
          failureThreshold: 10
          httpGet:
            path: /healthz/
            port: {{ .Values.api.service.targetPort }}
            scheme: {{ .Values.api.service.scheme | default "HTTP" }}
            {{- if .Values.allowedHosts }}
            httpHeaders:
              - name: Host
                value: {{ template "polyaxon.fullname" . }}-api
            {{- end }}
          initialDelaySeconds: 120
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 2
        readinessProbe:
          failureThreshold: 30
          httpGet:
            path: /healthz/
            port: {{ .Values.api.service.targetPort }}
            scheme: {{ .Values.api.service.scheme | default "HTTP" }}
            {{- if .Values.allowedHosts }}
            httpHeaders:
              - name: Host
                value: {{ template "polyaxon.fullname" . }}-api
            {{- end }}
          initialDelaySeconds: 120
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 2
        resources:
          requests:
{{ toYaml .Values.api.resources.requests | indent 12 }}
          {{- if .Values.limitResources }}
          limits:
{{ toYaml .Values.api.resources.limits | indent 12 }}
          {{- end }}
