apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "polyaxon.fullname" . }}-api
  annotations:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
{{ include "config.checksum.platform" . | indent 4 }}
  labels:
{{ include "config.labels.apps.api" . | indent 4 }}
{{ include "config.labels.common" . | indent 4 }}
{{ include "config.labels.roles.coreApi" . | indent 4 }}
spec:
  replicas: {{ .Values.api.replicas }}
  selector:
    matchLabels:
{{ include "config.labels.apps.api" . | indent 6 }}
  template:
    metadata:
      annotations:
        chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
{{ include "config.checksum.platform" . | indent 8 }}
      labels:
{{ include "config.labels.apps.api" . | indent 8 }}
{{ include "config.labels.common" . | indent 8 }}
{{ include "config.labels.roles.coreApi" . | indent 8 }}
    spec:
{{ include "securityContext" . | indent 6 }}
{{ include "config.scheduling" . | indent 6 }}
{{ include "config.agent.sa" . | indent 6 }}
{{ include "config.imagePullSecrets" . | indent 6}}
      containers:
      - name: {{ .Chart.Name }}-api
        image: "{{ .Values.api.image }}:{{ .Values.api.imageTag }}"
        imagePullPolicy: {{ .Values.api.imagePullPolicy }}
        ports:
        - containerPort: {{ .Values.api.service.targetPort }}
        envFrom:
{{ include "config.envFrom.common" . | indent 8 }}
{{ include "config.envFrom.secret" . | indent 8 }}
{{ include "config.envFrom.platform" . | indent 8 }}
{{ include "config.envFrom.proxies" . | indent 8 }}
        env:
{{ include "config.envs" . | indent 8 }}
{{ include "config.debugMode" . | indent 8 }}
        livenessProbe:
          httpGet:
            path: /healthz/
            port: {{ .Values.api.service.targetPort }}
            scheme: {{ .Values.api.service.scheme | default "HTTP" }}
            {{- if .Values.allowedHosts }}
            httpHeaders:
              - name: Host
                value: {{ template "polyaxon.fullname" . }}-api
            {{- end }}
          initialDelaySeconds: 60
          periodSeconds: 30
          successThreshold: 1
          failureThreshold: 10
          timeoutSeconds: 2
        readinessProbe:
          httpGet:
            path: /healthz/
            port: {{ .Values.api.service.targetPort }}
            scheme: {{ .Values.api.service.scheme | default "HTTP" }}
            {{- if .Values.allowedHosts }}
            httpHeaders:
              - name: Host
                value: {{ template "polyaxon.fullname" . }}-api
            {{- end }}
          initialDelaySeconds: 60
          periodSeconds: 30
          successThreshold: 1
          failureThreshold: 10
          timeoutSeconds: 2
        resources:
          requests:
{{ toYaml .Values.api.resources.requests | indent 12 }}
          {{- if .Values.limitResources }}
          limits:
{{ toYaml .Values.api.resources.limits | indent 12 }}
          {{- end }}
