{{- if .Values.gateway.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "polyaxon.fullname" . }}-gateway
  annotations:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    checksum/common-config: {{ include (print $.Template.BasePath "/common-cm.yaml") . | sha256sum }}
    checksum/proxies-config: {{ include (print $.Template.BasePath "/proxies-cm.yaml") . | sha256sum }}
  labels:
{{ include "config.labels.common" . | indent 4 }}
{{ include "config.labels.roles.coreApi" . | indent 4 }}
{{ include "config.labels.apps.gateway" . | indent 4 }}
spec:
  replicas: {{ .Values.gateway.replicas }}
  selector:
    matchLabels:
{{ include "config.labels.apps.gateway" . | indent 6 }}
  template:
    metadata:
      annotations:
        chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
        checksum/common-config: {{ include (print $.Template.BasePath "/common-cm.yaml") . | sha256sum }}
        checksum/proxies-config: {{ include (print $.Template.BasePath "/proxies-cm.yaml") . | sha256sum }}
      labels:
{{ include "config.labels.common" . | indent 8 }}
{{ include "config.labels.roles.coreApi" . | indent 8 }}
{{ include "config.labels.apps.gateway" . | indent 8 }}
    spec:
{{ include "securityContext" . | indent 6 }}
{{ include "config.scheduling" . | indent 6 }}
{{ include "config.sa" . | indent 6 }}
{{ include "config.imagePullSecrets" . | indent 6}}
      containers:
      - name: {{ .Chart.Name }}-gateway
        image: "{{ .Values.gateway.image }}:{{ .Values.gateway.imageTag }}"
        imagePullPolicy: {{ .Values.gateway.imagePullPolicy }}
        ports:
        - containerPort: {{ .Values.gateway.service.targetPort }}
        envFrom:
{{ include "config.envFrom.common" . | indent 8 }}
{{ include "config.envFrom.proxies" . | indent 8 }}
        env:
{{ include "config.debugMode" . | indent 8 }}
        volumeMounts:
{{ include "ssl.mount" . | indent 8}}
        livenessProbe:
          failureThreshold: 10
          httpGet:
            path: /healthz/
            port: {{ .Values.gateway.service.targetPort }}
            scheme: {{ .Values.gateway.service.scheme | default "HTTP" }}
          initialDelaySeconds: 120
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 2
        readinessProbe:
          failureThreshold: 30
          httpGet:
            path: /healthz/
            port: {{ .Values.gateway.service.targetPort }}
            scheme: {{ .Values.gateway.service.scheme | default "HTTP" }}
            {{- if .Values.allowedHosts }}
            httpHeaders:
              - name: Host
                value: {{ template "polyaxon.fullname" . }}-gateway
            {{- end }}
          initialDelaySeconds: 120
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 2
        resources:
          requests:
{{ toYaml .Values.gateway.resources.requests | indent 12 }}
          {{- if .Values.limitResources }}
          limits:
{{ toYaml .Values.gateway.resources.limits | indent 12 }}
          {{- end }}
      volumes:
{{ include "ssl.volume" . | indent 6}}
{{- end }}
