{{- if (not .Values.secret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "polyaxon.fullname" . }}-secret
  labels:
    app: {{ template "polyaxon.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    type: {{ .Values.types.core }}
    role: {{ .Values.roles.config }}
    app.kubernetes.io/name: {{ template "polyaxon.fullname" . }}-secret
    app.kubernetes.io/instance: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    app.kubernetes.io/version: "{{ .Chart.Version }}"
    app.kubernetes.io/part-of: {{ .Values.types.core }}
    app.kubernetes.io/component: {{ .Values.roles.config }}
    app.kubernetes.io/managed-by: "helm"
type: Opaque
data:
  {{- if .Values.polyaxonSecret }}
  POLYAXON_SECRET_KEY: {{ .Values.polyaxonSecret | b64enc | quote }}
  {{- else }}
  POLYAXON_SECRET_KEY: {{ randAlphaNum 60 | b64enc | quote }}
  {{- end }}
  {{- if .Values.polyaxonSecret }}
  POLYAXON_SECRET_INTERNAL_TOKEN: {{ .Values.internalToken | b64enc | quote }}
  {{- else }}
  POLYAXON_SECRET_INTERNAL_TOKEN: {{ randAlphaNum 60 | b64enc | quote }}
  {{- end }}
  {{- if .Values.user.password }}
  POLYAXON_ADMIN_PASSWORD: {{ .Values.user.password | b64enc | quote }}
  {{- else }}
  POLYAXON_ADMIN_PASSWORD: {{ randAlphaNum 16 | b64enc | quote }}
  {{- end }}
  {{- if .Values.email.hostPassword }}
  POLYAXON_EMAIL_HOST_PASSWORD: {{ .Values.email.hostPassword | b64enc | quote }}
  {{- end }}
  {{- if .Values.ldap.enabled }}
  POLYAXON_AUTH_LDAP_BIND_PASSWORD: {{ default "" .Values.ldap.bindPassword | b64enc | quote }}
  {{- end }}
  {{- if .Values.organizationKey }}
  POLYAXON_ORGANIZATION_KEY: {{ .Values.organizationKey | quote }}
  {{- end }}

{{ if not .Values.postgresql.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "polyaxon.fullname" . }}-postgresql-secret
  labels:
    app: {{ template "polyaxon.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    type: {{ .Values.types.core }}
    role: {{ .Values.roles.config }}
    app.kubernetes.io/name: {{ template "polyaxon.fullname" . }}-postgresql-secret
    app.kubernetes.io/instance: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    app.kubernetes.io/version: "{{ .Chart.Version }}"
    app.kubernetes.io/part-of: {{ .Values.types.core }}
    app.kubernetes.io/component: {{ .Values.roles.config }}
    app.kubernetes.io/managed-by: "helm"
type: Opaque
data:
  {{- if .Values.externalServices.postgresql.password }}
  postgresql-password:  {{ .Values.externalServices.postgresql.password | b64enc | quote }}
  {{- else }}
  postgresql-password: {{ randAlphaNum 10 | b64enc | quote }}
  {{- end -}}
{{- end -}}

{{ if and .Values.scheduler.enabled (not .Values.redis.enabled) .Values.externalServices.redis.usePassword }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "polyaxon.fullname" . }}-redis-secret
  labels:
    app: {{ template "polyaxon.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    type: {{ .Values.types.core }}
    role: {{ .Values.roles.config }}
    app.kubernetes.io/name: {{ template "polyaxon.fullname" . }}-redis-secret
    app.kubernetes.io/instance: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    app.kubernetes.io/version: "{{ .Chart.Version }}"
    app.kubernetes.io/part-of: {{ .Values.types.core }}
    app.kubernetes.io/component: {{ .Values.roles.config }}
    app.kubernetes.io/managed-by: "helm"
type: Opaque
data:
  {{- if .Values.externalServices.redis.password }}
  redis-password:  {{ .Values.externalServices.redis.password | b64enc | quote }}
  {{- else }}
  redis-password: {{ randAlphaNum 10 | b64enc | quote }}
  {{- end -}}
{{- end -}}


{{ if and .Values.scheduler.enabled (not (index .Values "rabbitmq-ha").enabled) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "polyaxon.fullname" . }}-rabbitmq-secret
  labels:
    app: {{ template "polyaxon.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    type: {{ .Values.types.core }}
    role: {{ .Values.roles.config }}
    app.kubernetes.io/name: {{ template "polyaxon.fullname" . }}-rabbitmq-secret
    app.kubernetes.io/instance: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    app.kubernetes.io/version: "{{ .Chart.Version }}"
    app.kubernetes.io/part-of: {{ .Values.types.core }}
    app.kubernetes.io/component: {{ .Values.roles.config }}
    app.kubernetes.io/managed-by: "helm"
type: Opaque
data:
  {{- if .Values.externalServices.rabbitmq.password }}
  rabbitmq-password:  {{ .Values.externalServices.rabbitmq.password | b64enc | quote }}
  {{- else }}
  rabbitmq-password: {{ randAlphaNum 10 | b64enc | quote }}
  {{- end -}}
{{- end -}}
{{- end -}}
