{{- if (not .Values.secret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "polyaxon.fullname" . }}-platform-secret
  labels:
    app.kubernetes.io/name: {{ template "polyaxon.fullname" . }}-platform-secret
{{ include "config.labels.common" . | indent 4 }}
{{ include "config.labels.roles.coreConfig" . | indent 4 }}
type: Opaque
data:
  {{- if .Values.polyaxonSecret }}
  POLYAXON_SECRET_KEY: {{ .Values.polyaxonSecret | b64enc | quote }}
  {{- else }}
  POLYAXON_SECRET_KEY: {{ randAlphaNum 60 | b64enc | quote }}
  {{- end }}
  {{- if .Values.polyaxonSecret }}
  POLYAXON_SECRET_INTERNAL_TOKEN: {{ .Values.internalToken | b64enc | quote }}
  {{- else }}
  POLYAXON_SECRET_INTERNAL_TOKEN: {{ randAlphaNum 60 | b64enc | quote }}
  {{- end }}
  {{- if .Values.user.password }}
  POLYAXON_ADMIN_PASSWORD: {{ .Values.user.password | b64enc | quote }}
  {{- else }}
  POLYAXON_ADMIN_PASSWORD: {{ randAlphaNum 16 | b64enc | quote }}
  {{- end }}
  {{- if .Values.email.hostPassword }}
  POLYAXON_EMAIL_HOST_PASSWORD: {{ .Values.email.hostPassword | b64enc | quote }}
  {{- end }}
  {{- if .Values.ldap.enabled }}
  POLYAXON_AUTH_LDAP_BIND_PASSWORD: {{ default "" .Values.ldap.bindPassword | b64enc | quote }}
  {{- end }}
  {{- if .Values.organizationKey }}
  POLYAXON_ORGANIZATION_KEY: {{ .Values.organizationKey | b64enc | quote }}
  {{- end }}
  {{- if .Values.externalServices.analytics.enabled }}
  POLYAXON_ANALYTICS_OPTIONS: {{ toJson .Values.externalServices.analytics.options | b64enc | quote }}
  {{- end }}
  {{- if .Values.externalServices.transactions.enabled }}
  POLYAXON_TRANSACTIONS_OPTIONS: {{ toJson .Values.externalServices.transactions.options | b64enc | quote }}
  {{- end }}
  {{- if .Values.externalServices.errors.enabled }}
  POLYAXON_ERRORS_OPTIONS: {{ toJson .Values.externalServices.errors.options | b64enc | quote }}
  {{- end }}
  {{- if .Values.externalServices.metrics.enabled }}
  POLYAXON_METRICS_OPTIONS: {{ toJson .Values.externalServices.metrics.options | b64enc | quote }}
  {{- end }}
  {{- if .Values.externalServices.auth.github.enabled }}
  POLYAXON_AUTH_GITHUB_OPTIONS: {{ toJson .Values.externalServices.auth.github.options | b64enc | quote }}
  {{- end }}
  {{- if .Values.externalServices.auth.gitlab.enabled }}
  POLYAXON_AUTH_GITLAB_OPTIONS: {{ toJson .Values.externalServices.auth.gitlab.options | b64enc | quote }}
  {{- end }}
  {{- if .Values.externalServices.auth.bitbucket.enabled }}
  POLYAXON_AUTH_BITBUCKET_OPTIONS: {{ toJson .Values.externalServices.auth.bitbucket.options | b64enc | quote }}
  {{- end }}
  {{- if .Values.externalServices.auth.google.enabled }}
  POLYAXON_AUTH_GOOGLE_OPTIONS: {{ toJson .Values.externalServices.auth.google.options | b64enc | quote }}
  {{- end }}
  {{- if .Values.externalServices.auth.saml.enabled }}
  POLYAXON_AUTH_SAML_OPTIONS: {{ toJson .Values.externalServices.auth.saml.options | b64enc | quote }}
  {{- end }}

{{ if not .Values.postgresql.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "polyaxon.fullname" . }}-postgresql-secret
  labels:
    app.kubernetes.io/name: {{ template "polyaxon.fullname" . }}-postgresql-secret
{{ include "config.labels.common" . | indent 4 }}
{{ include "config.labels.roles.coreConfig" . | indent 4 }}
type: Opaque
data:
  {{- if .Values.externalServices.postgresql.password }}
  postgresql-password:  {{ .Values.externalServices.postgresql.password | b64enc | quote }}
  {{- else }}
  postgresql-password: {{ randAlphaNum 10 | b64enc | quote }}
  {{- end -}}
{{- end -}}

{{ if and .Values.scheduler.enabled (not .Values.redis.enabled) .Values.externalServices.redis.usePassword }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "polyaxon.fullname" . }}-redis-secret
  labels:
    app.kubernetes.io/name: {{ template "polyaxon.fullname" . }}-redis-secret
{{ include "config.labels.common" . | indent 4 }}
{{ include "config.labels.roles.coreConfig" . | indent 4 }}
type: Opaque
data:
  {{- if .Values.externalServices.redis.password }}
  redis-password:  {{ .Values.externalServices.redis.password | b64enc | quote }}
  {{- else }}
  redis-password: {{ randAlphaNum 10 | b64enc | quote }}
  {{- end -}}
{{- end -}}


{{ if and .Values.scheduler.enabled (not (index .Values "rabbitmq-ha").enabled) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "polyaxon.fullname" . }}-rabbitmq-secret
  labels:
    app.kubernetes.io/name: {{ template "polyaxon.fullname" . }}-rabbitmq-secret
{{ include "config.labels.common" . | indent 4 }}
{{ include "config.labels.roles.coreConfig" . | indent 4 }}
type: Opaque
data:
  {{- if .Values.externalServices.rabbitmq.password }}
  rabbitmq-password:  {{ .Values.externalServices.rabbitmq.password | b64enc | quote }}
  {{- else }}
  rabbitmq-password: {{ randAlphaNum 10 | b64enc | quote }}
  {{- end -}}
{{- end -}}
{{- end -}}
