{{- if .Values.scheduler.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "polyaxon.fullname" . }}-scheduler
  annotations:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
{{ include "config.checksum.platform" . | indent 4 }}
  labels:
    app.kubernetes.io/name: {{ template "polyaxon.fullname" . }}-scheduler
{{ include "config.labels.common" . | indent 4 }}
{{ include "config.labels.roles.coreWorker" . | indent 4 }}
spec:
  replicas: {{ .Values.scheduler.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ template "polyaxon.fullname" . }}-scheduler
  template:
    metadata:
      annotations:
        chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
{{ include "config.checksum.platform" . | indent 8 }}
      labels:
        app.kubernetes.io/name: {{ template "polyaxon.fullname" . }}-scheduler
{{ include "config.labels.common" . | indent 8 }}
{{ include "config.labels.roles.coreWorker" . | indent 8 }}
    spec:
{{ include "securityContext" . | indent 6 }}
{{ include "config.scheduling" . | indent 6 }}
{{ include "config.agent.sa" . | indent 6 }}
{{ include "config.imagePullSecrets" . | indent 6}}
      containers:
      - name: {{ .Chart.Name }}-scheduler
        image: "{{ .Values.scheduler.image }}:{{ .Values.scheduler.imageTag }}"
        imagePullPolicy: {{ .Values.scheduler.imagePullPolicy }}
        args: ["scheduler", "--concurrency={{ .Values.scheduler.concurrency }}"]
        envFrom:
{{ include "config.envFrom.common" . | indent 8 }}
{{ include "config.envFrom.secret" . | indent 8 }}
{{ include "config.envFrom.platform" . | indent 8 }}
{{ include "config.envFrom.proxies" . | indent 8 }}
        env:
{{ include "config.envs" . | indent 8 }}
{{ include "config.celery.scheduler" . | indent 8 }}
        livenessProbe:
          exec:
            command: ["/bin/bash", "./entrypoint.sh", "healthz"]
          initialDelaySeconds: 60
          periodSeconds: 60
          successThreshold: 1
          failureThreshold: 10
          timeoutSeconds: 10
        readinessProbe:
          exec:
            command: ["/bin/bash", "./entrypoint.sh", "healthz"]
          initialDelaySeconds: 60
          periodSeconds: 60
          successThreshold: 1
          failureThreshold: 10
          timeoutSeconds: 2
        resources:
          requests:
{{ toYaml .Values.scheduler.resources.requests | indent 12 }}
          {{- if .Values.limitResources }}
          limits:
{{ toYaml .Values.scheduler.resources.limits | indent 12 }}
          {{- end }}
{{- end }}
