{{- if .Values.gateway.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "polyaxon.fullname" . }}-gateway
  labels:
    app: {{ template "polyaxon.fullname" . }}-gateway
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    type: {{ .Values.types.core }}
    role: {{ .Values.roles.api }}
    app.kubernetes.io/name: {{ template "polyaxon.fullname" . }}-gateway
    app.kubernetes.io/instance: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    app.kubernetes.io/version: "{{ .Chart.Version }}"
    app.kubernetes.io/part-of: {{ .Values.types.core }}
    app.kubernetes.io/component: {{ .Values.roles.api }}
    app.kubernetes.io/managed-by: "helm"
  {{- with .Values.gateway.service.annotations }}
  annotations:
  {{ toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.gateway.service.type }}
  selector:
    app: {{ template "polyaxon.fullname" . }}-gateway
  ports:
  - port: {{ .Values.gateway.service.port }}
    targetPort: {{ .Values.gateway.service.targetPort }}
    {{ if eq .Values.gateway.service.type "NodePort" -}}
    nodePort: {{ .Values.gateway.service.nodePort }}
    {{- end }}
    name: {{ .Values.gateway.service.name }}
{{- end }}
