{{- if or .Values.agent.enabled (not .Values.organizationKey) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "polyaxon.fullname" . }}-agent-config
  labels:
    app.kubernetes.io/name: {{ template "polyaxon.fullname" . }}-agent-config
{{ include "config.labels.common" . | indent 4 }}
{{ include "config.labels.roles.coreConfig" . | indent 4 }}
data:
  POLYAXON_K8S_IN_CLUSTER: "true"
  POLYAXON_SET_AGENT: "true"
  {{- if .Values.agent.instance }}
  POLYAXON_AGENT_INSTANCE: {{ .Values.agent.instance | quote }}
  {{- end }}
  {{- if .Values.artifactsStore }}
  POLYAXON_AGENT_ARTIFACTS_STORE: {{ toJson .Values.artifactsStore | quote }}
  {{- else }}
  POLYAXON_AGENT_ARTIFACTS_STORE: {{ toJson .Values.defaultArtifactsStore | quote }}
  {{- end }}
  {{- if .Values.connections }}
  POLYAXON_AGENT_CONNECTIONS: {{ toJson .Values.connections | quote }}
  {{- end }}
  {{- if .Values.notificationConnections }}
  POLYAXON_AGENT_NOTIFICATION_CONNECTIONS: {{ toJson .Values.notificationConnections | quote }}
  {{- end }}
  POLYAXON_AGENT_SIDECAR: {{ toJson .Values.sidecar | quote }}
  POLYAXON_AGENT_INIT: {{ toJson .Values.init | quote }}
  POLYAXON_AGENT_RUNS_SA: {{ template "polyaxon.fullname" . }}-runs-sa
  {{- if .Values.agentSecret }}
  POLYAXON_AGENT_SECRET_NAME: {{ .Values.agentSecret | quote }}
  {{- else }}
  {{- if .Values.agent.token }}
  POLYAXON_AGENT_SECRET_NAME: {{ template "polyaxon.fullname" . }}-agent-secret
  {{- end }}
  {{- if .Values.agent.isReplica }}
  POLYAXON_AGENT_IS_REPLICA: {{ .Values.agent.isReplica | quote }}
  {{- end }}
  {{- end }}
  POLYAXON_AGENT_COMPRESSED_LOGS: {{ .Values.agent.compressedLogs | quote }}
  {{- if .Values.operator.maxConcurrentReconciles }}
  POLYAXON_MAX_CONCURRENT_RECONCILES: {{ .Values.operator.maxConcurrentReconciles | quote }}
  {{- end }}
  {{- if .Values.operators.tfjob }}
  POLYAXON_TFJOB_ENABLED: "true"
  {{- end }}
  {{- if .Values.operators.pytorchjob }}
  POLYAXON_PYTORCH_JOB_ENABLED: "true"
  {{- end }}
  {{- if .Values.operators.mpijob }}
  POLYAXON_MPIJOB_ENABLED: "true"
  {{- end }}
  {{- if .Values.operators.sparkjob }}
  POLYAXON_SPARK_JOB_ENABLED: "true"
  {{- end }}
{{- end }}
