{{- if .Values.agent.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "polyaxon.fullname" . }}-agent
  annotations:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
{{ include "config.checksum.agent" . | indent 4 }}
  labels:
    app.kubernetes.io/name: {{ template "polyaxon.fullname" . }}-agent
{{ include "config.labels.common" . | indent 4 }}
{{ include "config.labels.roles.coreWorker" . | indent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ template "polyaxon.fullname" . }}-agent
  template:
    metadata:
      annotations:
        chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
{{ include "config.checksum.agent" . | indent 8 }}
      labels:
        app.kubernetes.io/name: {{ template "polyaxon.fullname" . }}-agent
{{ include "config.labels.common" . | indent 8 }}
{{ include "config.labels.roles.coreWorker" . | indent 8 }}
    spec:
{{ include "securityContext" . | indent 6 }}
{{ include "config.scheduling" . | indent 6 }}
{{ include "config.sa" . | indent 6 }}
{{ include "config.imagePullSecrets" . | indent 6}}
      containers:
      - name: {{ .Chart.Name }}-agent
        image: "{{ .Values.agent.image }}:{{ .Values.agent.imageTag }}"
        imagePullPolicy: {{ .Values.agent.imagePullPolicy }}
        envFrom:
{{ include "config.envFrom.common" . | indent 8 }}
{{ include "config.envFrom.agent" . | indent 8 }}
        env:
{{ include "config.debugMode" . | indent 8 }}
        resources:
          requests:
{{ toYaml .Values.agent.resources.requests | indent 12 }}
          {{- if .Values.limitResources }}
          limits:
{{ toYaml .Values.agent.resources.limits | indent 12 }}
          {{- end }}
{{- end }}
