apiVersion: v1
description: Kubeflow TFJob integration with Polyaxon
name: tfjob
version: 1.3.0
appVersion: 1.3.0
keywords:
  - deep learning
  - a.i.
  - machine learning
  - infrastructure
sources:
  - https://github.com/polyaxon
home: https://polyaxon.com
icon: https://raw.githubusercontent.com/polyaxon/polyaxon/master/artifacts/logo/logo-small.png
maintainers:
  - name: Polyaxon
    email: contact@polyaxon.com
    url: polyaxon.com
