{{- if .Values.metrics.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "polyaxon.fullname" . }}-metrics
  labels:
    app.kubernetes.io/name: {{ template "polyaxon.fullname" . }}-metrics
{{ include "config.labels.common" . | indent 4 }}
{{ include "config.labels.roles.coreHelpers" . | indent 4 }}
{{- if .Values.metrics.service.labels }}
{{ toYaml .Values.metrics.service.labels | indent 4 }}
{{- end }}
spec:
  type: {{ .Values.metrics.service.type }}
  ports:
  - port: 9102
    targetPort: 9102
    protocol: TCP
    name: metrics
  - port: 9125
    targetPort: 9125
    protocol: UDP
    name: statsd
  selector:
    app.kubernetes.io/name: {{ template "polyaxon.fullname" . }}-metrics
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
