namespace: polyaxon

rbac:
  enabled: true

types:
  agent: "polyaxon-agent"

roles:
  config: "polyaxon-config"
  agent: "polyaxon-agent"

api:
  host: https://*.polyaxon.com
  token: token-default-value

gateway:
  image: polyaxon/polyaxon-gateway
  imageTag: 1.0.9
  imagePullPolicy: Always
  replicas: 1
  resources:
    limits:
      cpu: 1000m
      memory: 2000Mi
    requests:
      cpu: 128m
      memory: 300Mi

  service:
    name: gateway
    type: LoadBalancer
    port: 80
    targetPort: 80
    nodePort: 31833
    annotations: {}

streams:
  image: polyaxon/polyaxon-streams
  imageTag: 1.0.9
  imagePullPolicy: Always
  replicas: 1
  resources:
    limits:
      cpu: 1000m
      memory: 2000Mi
    requests:
      cpu: 128m
      memory: 300Mi

  service:
    name: streams
    type: ClusterIP
    port: 80
    targetPort: 80
    nodePort: 31822
    annotations: {}

  hpa:
    enabled: false
    cputhreshold: 70
    minpods: 1
    maxpods: 4

init:
  image: polyaxon/polyaxon-init
  imageTag: 1.0.9
  imagePullPolicy: Always
  resources:
    limits:
      cpu: 1000m
      memory: 2000Mi
    requests:
      cpu: 128m
      memory: 300Mi

sidecar:
  image: polyaxon/polyaxon-sidecar
  imageTag: 1.0.9
  imagePullPolicy: Always
  sleepInterval: 10
  syncInterval: 10
  resources:
    limits:
      cpu: 1000m
      memory: 2000Mi
    requests:
      cpu: 128m
      memory: 300Mi

agent:
  token:
  instance:
  enabled: false
  image: polyaxon/polyaxon-agent
  imageTag: 1.0.9
  imagePullPolicy: Always
  resources:
    limits:
      cpu: 1000m
      memory: 2000Mi
    requests:
      cpu: 128m
      memory: 300Mi

operator:
  enabled: false
  image: polyaxon/polyaxon-operator
  imageTag: 1.0.9
  imagePullPolicy: Always
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 20Mi

securityContext:
  enabled: false
  user: 2222
  group: 2222

imagePullSecrets: []

artifactsStore: {}
connections: []
notificationConnections: []
