apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: mpijobs.kubeflow.org
spec:
  group: kubeflow.org
  version: v1alpha2
  scope: Namespaced
  names:
    plural: mpijobs
    singular: mpijob
    kind: MPIJob
    shortNames:
    - mj
    - mpij
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        spec:
          properties:
            slotsPerWorker:
              type: integer
              minimum: 1
            mpiReplicaSpecs:
              properties:
                Launcher:
                  properties:
                    replicas:
                      type: integer
                      minimum: 1
                      maximum: 1
                Worker:
                  properties:
                    replicas:
                      type: integer
                      minimum: 1
