{{- if .Values.ingress.enabled -}}
{{- $secretName := printf "%s-%s" .Release.Name "tls" -}}

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ template "polyaxon.fullname" . }}-ingress
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ template "polyaxon.fullname" . }}-ingress
{{ include "config.labels.common" . | indent 4 }}
{{ include "config.labels.roles.coreApi" . | indent 4 }}
    {{- with .Values.ingress.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
{{ toYaml .Values.ingress.annotations | indent 4 }}
spec:
  rules:
  - host: {{ .Values.ingress.hostName | quote }}
    http:
      paths:
      - path: {{ default "/" .Values.ingress.path | quote }}
{{ include "config.ingress.backend" . | indent 8 }}
      {{- range .Values.ingress.extraPaths }}
      - path: {{ .path | quote }}
        pathType: {{ default "Prefix" .Values.ingress.pathType }}
        backend:
          service:
            name: {{ .backend.service.name }}
            port:
              number: {{ .backend.service.port }}
      {{- end }}
  {{- if (not (empty .Values.ingress.tls)) }}
  tls:
    {{ toYaml .Values.ingress.tls | nindent 4 }}
  {{- end -}}
{{- end }}
