apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "polyaxon.fullname" . }}-proxies-config
  labels:
    app.kubernetes.io/name: {{ template "polyaxon.fullname" . }}-proxies-config
{{ include "config.labels.common" . | indent 4 }}
{{ include "config.labels.roles.coreConfig" . | indent 4 }}
data:
  # Cluster
  POLYAXON_HOST: "{{ template "gateway.scheme" . }}://{{ template "gateway.host" . }}:{{ template "gateway.port" . }}"
  {{- if .Values.streams.enabled }}
  POLYAXON_PROXY_STREAMS_PORT: "{{ template "proxies.streams.port" . }}"
  POLYAXON_PROXY_STREAMS_HOST: {{ template "proxies.streams.host" . }}
  {{- end }}
  POLYAXON_PROXY_API_PORT: "{{ template "proxies.api.port" . }}"
  POLYAXON_PROXY_API_HOST: {{ template "proxies.api.host" . }}
  POLYAXON_PROXY_API_USE_RESOLVER: "{{ template "proxies.api.useResolver" . }}"
  {{- if .Values.auth.enabled }}
  POLYAXON_PROXY_AUTH_ENABLED: {{ .Values.auth.enabled | quote }}
  {{- if .Values.auth.external }}
  POLYAXON_PROXY_AUTH_EXTERNAL: {{ .Values.auth.external | quote }}
  {{- end }}
  {{- if .Values.auth.useResolver }}
  POLYAXON_PROXY_AUTH_USE_RESOLVER: {{ .Values.auth.useResolver | quote }}
  {{- end }}
  {{- end }}
  # DNS
  POLYAXON_DNS_USE_RESOLVER: "true"
  {{- if .Values.dns.backend }}
  POLYAXON_DNS_BACKEND: {{ .Values.dns.backend | quote }}
  {{- end }}
  {{- if .Values.dns.customCluster }}
  POLYAXON_DNS_CUSTOM_CLUSTER: {{ .Values.dns.customCluster | quote }}
  {{- end }}
  {{- if .Values.dns.POLYAXON_DNS_PREFIX }}
  POLYAXON_DNS_PREFIX: {{ .Values.dns.prefix | quote }}
  {{- end }}
  # SSL
  POLYAXON_SSL_ENABLED: "{{ template "ssl.enabled" . }}"
  POLYAXON_SSL_REDIRECT_ENABLED: "{{ template "ssl.redirect.enabled" . }}"
  {{- if and .Values.ssl.enabled .Values.ssl.secretName .Values.ssl.path }}
  POLYAXON_SSL_PATH:  {{ .Values.ssl.path | quote }}
  {{- end }}
  # Services
  {{- if (not (empty .Values.services)) }}
  POLYAXON_PROXY_SERVICES_PORT: {{ .Values.services.port | quote }}
  {{- end }}
  # UI
  {{- if (not (eq (.Values.ui.enabled | toString) "<nil>")) }}
  POLYAXON_UI_ENABLED: {{ .Values.ui.enabled | quote }}
  {{- end }}
  {{- if (not (eq (.Values.ui.adminEnabled | toString) "<nil>")) }}
  POLYAXON_UI_ADMIN_ENABLED: {{ .Values.ui.adminEnabled | quote }}
  {{- end }}
  {{- if .Values.ui.offline }}
  POLYAXON_UI_OFFLINE: {{ .Values.ui.offline | quote }}
  {{- end }}
  {{- if .Values.ui.staticUrl }}
  POLYAXON_STATIC_URL: {{ .Values.ui.staticUrl | quote }}
  {{- end }}
  {{- if .Values.istio.enabled }}
  POLYAXON_ISTIO_ENABLED: "true"
  {{- end }}
  {{- if .Values.istio.gateway }}
  POLYAXON_ISTIO_GATEWAY: {{ .Values.istio.gateway  | quote }}
  {{- end }}
  {{- if .Values.istio.tlsMode }}
  POLYAXON_ISTIO_TLS_MODE: {{ .Values.istio.tlsMode  | quote }}
  {{- end }}
  {{- if .Values.istio.prefix }}
  POLYAXON_ISTIO_PREFIX: {{ .Values.istio.prefix  | quote }}
  {{- end }}
  {{- if .Values.istio.timeout }}
  POLYAXON_ISTIO_TIMEOUT: {{ .Values.istio.timeout  | quote }}
  {{- end }}
