dependencies:
  - name: postgresql
    version: 0.8.7
    repository: https://kubernetes-charts.storage.googleapis.com/
    condition: postgresql.enabled
  - name: rabbitmq-ha
    version: 1.34.0
    repository: https://kubernetes-charts.storage.googleapis.com/
    condition: rabbitmq-ha.enabled
  - name: redis
    version: 9.3.3
    repository: https://kubernetes-charts.storage.googleapis.com/
    condition: redis.enabled
  - name: docker-registry
    version: 1.8.3
    repository: https://kubernetes-charts.storage.googleapis.com/
    condition: docker-registry.enabled
