{{- if and .Values.streams.enabled .Values.streams.hpa.enabled -}}
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ template "polyaxon.fullname" . }}-streams
  labels:
    app: {{ template "polyaxon.fullname" . }}-streams
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    type: {{ .Values.types.core }}
    role: {{ .Values.roles.api }}
    app.kubernetes.io/name: {{ template "polyaxon.fullname" . }}-streams
    app.kubernetes.io/instance: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    app.kubernetes.io/version: "{{ .Chart.Version }}"
    app.kubernetes.io/part-of: {{ .Values.types.core }}
    app.kubernetes.io/component: {{ .Values.roles.api }}
    app.kubernetes.io/managed-by: "helm"
spec:
  scaleTargetRef:
    kind: Deployment
    apiVersion: apps/v1
    name: {{ template "polyaxon.fullname" . }}-streams
  minReplicas: {{ .Values.streams.hpa.minpods }}
  maxReplicas: {{ .Values.streams.hpa.maxpods }}
  targetCPUUtilizationPercentage: {{ .Values.streams.hpa.cputhreshold }}
{{- end }}
