name: Polyaxon Api

on: [push, pull_request]

jobs:
  api:
#    if: github.event.comment.body == 'test platform'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - name: build
      run: |
        cmd/rebuild/npm-base
        cmd/rebuild/api
    - name: test-polycommon
      run: |
        cmd/test/api platform/polycommon module
    - name: test-coredb
      run: |
        cmd/test/api platform/coredb module --create-db
    - name: test-coreapi
      run: |
        cmd/test/api platform/coreapi
