name: Helm Charts

on: [push]

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.2
      - name: Fetch history
        run: git fetch --prune --unshallow
      - name: generate
        run: |
          cmd/helm/all
      - name: Run chart-testing (lint)
        uses: helm/chart-testing-action@v1.0.0
        with:
          command: lint
          config: config/ct.yaml
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.2
      - uses: azure/setup-helm@v1
      - uses: helm/kind-action@v1.0.0
      - name: generate
        run: |
          helm repo add stable https://kubernetes-charts.storage.googleapis.com
          cmd/helm/all
          cmd/helm/build
      - uses: actions/setup-python@v2.1.1
        with:
          python-version: 3.7
      - name: test
        env:
          KUBEBUILDER_CONTROLPLANE_START_TIMEOUT: 600s
        run: |
          export PATH=$HOME/.local/bin:/usr/local/bin:$PATH
          pip3 install -r core/requirements/requirements.txt -e core
          polyaxon admin deploy -f config/setup/default.yaml --manager-path=./charts/polyaxon
