name: Helm Charts

on: [push, pull_request]

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Fetch history
        run: git fetch --prune --unshallow
      - name: Run chart-testing (lint)
        uses: helm/chart-testing-action@v2.6.1
        with:
          command: lint
          config: charts/ci/ct.yaml
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config: [default, test-config1, test-config2]  # TODO: re-enable test-config3
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: azure/setup-helm@v3.5
      - uses: helm/kind-action@v1.9.0
      - name: generate
        run: |
          helm repo add bitnami https://charts.bitnami.com/bitnami
          cd charts
          helm dependency build polyaxon
          helm dependency build agent
      - uses: actions/setup-python@v5
        with:
          python-version: 3.9
      - name: test
        env:
          KUBEBUILDER_CONTROLPLANE_START_TIMEOUT: 600s
        run: |
          export PATH=$HOME/.local/bin:/usr/local/bin:$PATH
          pip3 install -r charts/ci/master-requirements.txt
          polyaxon admin deploy -f charts/ci/${{ matrix.config }}.yml --manager-path=charts/polyaxon
          polyaxon admin teardown
