name: "CLA Assistant"
on:
  issue_comment:
    types: [created]
  pull_request_target:
    types: [opened,closed,synchronize]

jobs:
  ContributorLicenseAgreement:
    runs-on: ubuntu-latest
    steps:
      - name: "CLA Assistant"
        if: (github.event.comment.body == 'recheck' || github.event.comment.body == 'I have read the CLA Document and I hereby sign the CLA') || github.event_name == 'pull_request_target'
        # Beta Release
        uses: cla-assistant/github-action@v2.1.2-beta
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # the below token should have repo scope and must be manually added by you in the repository's secret
          PERSONAL_ACCESS_TOKEN : ${{ secrets.PAT_CLATOOL }}
        with:
          path-to-signatures: 'config/cla/signatures/v1/cla.json'
          path-to-document: 'https://github.com/polyaxon/polyaxon/blob/main/config/cla/terms/v1.0.md'
          # branch should not be protected
          branch: 'master'
          allowlist: dependabot[bot]
