name: MLOperator

on: [push, pull_request]

jobs:
  operator:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v6
    - uses: actions/checkout@v6
      with:
        submodules: true
    - name: Running Tests
      run: |
        cd mloperator
        go mod tidy
        make test
