name: Polyaxon Operator

on: [push, pull_request]

jobs:
  operator:
#    if: github.event.comment.body == 'test worker'
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.13
      uses: actions/setup-go@v2.1.4
      with:
        go-version: 1.13
    - uses: actions/checkout@v2.3.5
    - uses: helm/kind-action@v1.2.0
    - name: test
      env:
        KUBEBUILDER_CONTROLPLANE_START_TIMEOUT: 600s
      run: |
        OS=$(go env GOOS)
        ARCH=$(go env GOARCH)
        KUBEBUILDER_VERSION=2.3.1
        # download kubebuilder and extract it to tmp
        curl -L https://github.com/kubernetes-sigs/kubebuilder/releases/download/v${KUBEBUILDER_VERSION}/kubebuilder_${KUBEBUILDER_VERSION}_${OS}_${ARCH}.tar.gz | tar -xz -C /tmp/
        sudo mv /tmp/kubebuilder_2.3.1_${OS}_${ARCH} /usr/local/kubebuilder
        export PATH=$PATH:/usr/local/kubebuilder/bin
        cd operator
        go version
        go install
        make github-action
