name: Polyaxon Operator

on: [push]

jobs:
  operator:
#    if: github.event.comment.body == 'test worker'
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.13
      uses: actions/setup-go@v2.1.1
      with:
        go-version: 1.13
    - uses: actions/checkout@v2.3.1
    - uses: helm/kind-action@v1.0.0-rc.1
    - name: test
      env:
        KUBEBUILDER_CONTROLPLANE_START_TIMEOUT: 600s
      run: |
        os=$(go env GOOS)
        arch=$(go env GOARCH)
        # download kubebuilder and extract it to tmp
        curl -L https://go.kubebuilder.io/dl/2.3.0/${os}/${arch} | tar -xz -C /tmp/
        sudo mv /tmp/kubebuilder_2.3.0_${os}_${arch} /usr/local/kubebuilder
        export PATH=$PATH:/usr/local/kubebuilder/bin
        cd operator
        go version
        go install
        make github-action
