apiVersion: v1
description: An enterprise-grade open-source platform for building, training, and monitoring large scale deep learning applications.
name: agent
version: 1.11.0
appVersion: 1.11.0
keywords:
  - deep learning
  - a.i.
  - machine learning
  - infrastructure
sources:
  - https://github.com/polyaxon
home: https://polyaxon.com
icon: https://raw.githubusercontent.com/polyaxon/polyaxon/master/artifacts/logo/logo-small.png
maintainers:
  - name: Polyaxon
    email: contact@polyaxon.com
    url: polyaxon.com
